### ISSUE TITLE
Requirements for the inference mode

### ISSUE THREAD

**Issue by kkedich** [Li-Chongyi/Zero-DCE#10]
I tried to create a conda environment with just pytorch and python3. But that didn't work, it seems that `opencv` is also required to run the test script `lowlight_test.py`.

The error when I used an environment with pytorch and python3:
+ Environment created by: `conda create --name zerodce_env pytorch==1.0.0 torchvision==0.2.1 cuda100 python=3.7 -c pytorch`

Error:
```
└─ $ ▶ python lowlight_test.py 
Traceback (most recent call last):
  File "lowlight_test.py", line 10, in <module>
    import dataloader
  File "/home/GIT/Zero-DCE/Zero-DCE_code/dataloader.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```
Adding the opencv to the requirements fix this, as in:
`conda create --name zerodce_env opencv pytorch==1.0.0 torchvision==0.2.1 cuda100 python=3.7 -c pytorch`

Maybe is nice to put the OpenCV in the requirements list, and also specify which version of python3 you used. Just for us to know which environment did you use and make easier the execution of the code. = )

**Comment by Li-Chongyi** [comment]
Hi,

Thank you so much for your kind reminding. I will revise the requirements.

Karina Bogdan <notifications@github.com> 于2020年10月2日周五 上午12:27写道：
