### ISSUE TITLE
[Question] If trained on custom data-set, what are the requirements(or suggestions)?

### ISSUE THREAD

**Issue by CaptainEven** [Li-Chongyi/Zero-DCE#26]
Thank you for your excellent work! I want to train Zero-DCE on a custom data-set, what should be considered for a good-performance model?

**Comment by Li-Chongyi** [comment]
Hi,

You may tune the weights of different losses. Its important to balance the
losses.

Even ***@***.***> 于2021年5月17日周一 下午2:31写道：

**Comment by CaptainEven** [comment]
@Li-Chongyi Thanks for your advice! I found severe mosaic blocks in some enhanced output like:

![1_HCA10315_A103026_20210516200100_939_1](https://user-images.githubusercontent.com/9303747/118577380-e219ac00-b7bc-11eb-8fea-52e2454cf761.jpg)
![1_HCA10315_A103026_20210516200100_939_1](https://user-images.githubusercontent.com/9303747/118577424-f3fb4f00-b7bc-11eb-97b3-380dddb93347.jpg)

**Comment by CaptainEven** [comment]
Do you have any advice for mitigating such mosaic?

**Comment by Li-Chongyi** [comment]
Hi,
This kind of curve-based method cannot denoise and remove mosaic. So, you
may need a preprocessing algorithm. Commonly, these issues should be solved
in the ISP pipeline.
Btw, our method is for academic use only. Thanks!

Even ***@***.***> 于2021年5月18日周二 上午9:40写道：

**Comment by CaptainEven** [comment]
Thanks for replying!
