### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by gwp2021** [Li-Chongyi/Zero-DCE#31]
Thank you for you sharing,but when I test the model, 'RuntimeError'is coming,the error code is:
''
python lowlight_test.py 
data/test_data/fig/025936506_K1214990_181_1_14.jpg
Traceback (most recent call last):
  File "lowlight_test.py", line 60, in <module>
    lowlight(image)
  File "lowlight_test.py", line 30, in lowlight
    data_lowlight = data_lowlight.permute(2,0,1)
RuntimeError: number of dims don't match in permute
''
could you tell me how can I solve the error,thank you

**Comment by jlin3333** [comment]
How to solve the error, thank you
