### ISSUE TITLE
请问为什么train或者test都会卡在网络实例化那部分？

### ISSUE THREAD

**Issue by MoeLightOvO** [Li-Chongyi/Zero-DCE#48]
具体来说就是运行刚开始就阻塞了，GPU也没有占用，例如在test中第33行 	DCE_net = model.enhance_net_nopool().cuda()
这一行之后就没有再继续了。
是否是因为环境的原因？

**Comment by MoeLightOvO** [comment]
已解决 30系显卡不支持11.0以下的CUDA版本了

**Comment by T-1009** [comment]
我在调试代码的时候

    _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步
请问你怎么解决的

**Comment by T-1009** [comment]
我的显卡是3060

**Comment by MoeLightOvO** [comment]
你试着训练过没？应该是作者的cuda版本低了 30系显卡的最低支持的cuda版本是11 torch版本应该是1.8吧&nbsp; 训练跟推理应该都会卡在这一步 可能版本记得不太清楚了 你再查一下资料

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上9:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)




 
我在调试代码的时候
 _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步  
请问你怎么解决的

**Comment by T-1009** [comment]
我是在跑作者源码里的lowlight test.py就会卡住



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)




 你试着训练过没？应该是作者的cuda版本低了 30系显卡的最低支持的cuda版本是11 torch版本应该是1.8吧&amp;nbsp; 训练跟推理应该都会卡在这一步 可能版本记得不太清楚了 你再查一下资料 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年12月19日(周二) 晚上9:13 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48) 
 
 
 
 
   
 我在调试代码的时候 
  _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步   
 请问你怎么解决的

**Comment by T-1009** [comment]
我安装的CUDA版本是12.2，但是我找不到对应的torch版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)




 你试着训练过没？应该是作者的cuda版本低了 30系显卡的最低支持的cuda版本是11 torch版本应该是1.8吧&amp;nbsp; 训练跟推理应该都会卡在这一步 可能版本记得不太清楚了 你再查一下资料 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年12月19日(周二) 晚上9:13 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48) 
 
 
 
 
   
 我在调试代码的时候 
  _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步   
 请问你怎么解决的

**Comment by MoeLightOvO** [comment]
如果方便的话在anaconda里创建个虚拟环境吧 pytorch官方有cuda版本对应的torch版本 并且可以用conda或者pip命令一键安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)




 我安装的CUDA版本是12.2，但是我找不到对应的torch版本 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年12月19日(周二) 晚上10:20 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48) 
 
 
 
 
  你试着训练过没？应该是作者的cuda版本低了 30系显卡的最低支持的cuda版本是11 torch版本应该是1.8吧&amp;amp;nbsp; 训练跟推理应该都会卡在这一步 可能版本记得不太清楚了 你再查一下资料  
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年12月19日(周二) 晚上9:13  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)  
   
   
   
   
     
  我在调试代码的时候  
   _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步    
  请问你怎么解决的

**Comment by T-1009** [comment]
你好，可以告诉我你的显卡是什么系列，然后你安装的CUDA版本和torch版本吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)




 如果方便的话在anaconda里创建个虚拟环境吧 pytorch官方有cuda版本对应的torch版本 并且可以用conda或者pip命令一键安装 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年12月19日(周二) 晚上10:53 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48) 
 
 
 
 
  我安装的CUDA版本是12.2，但是我找不到对应的torch版本  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年12月19日(周二) 晚上10:20  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)  
   
   
   
   
   你试着训练过没？应该是作者的cuda版本低了 30系显卡的最低支持的cuda版本是11 torch版本应该是1.8吧&amp;amp;amp;nbsp; 训练跟推理应该都会卡在这一步 可能版本记得不太清楚了 你再查一下资料   
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2023年12月19日(周二) 晚上9:13   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.***&amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;gt;;   
   主题: Re: [Li-Chongyi/Zero-DCE] 请问为什么train或者test都会卡在网络实例化那部分？ (Issue #48)   
     
     
     
     
       
   我在调试代码的时候   
    _, enhanced_image, _ = DCE_net(data_lowlight) # 卡在这步     
   请问你怎么解决的
