### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by tuvovan** [Li-Chongyi/Zero-DCE#8]
Hi, 

Thank you for the good paper.
I just re-produced your project here. Please kindly have a look and if there is any issue, please let me know.

https://github.com/tuvovan/Zero_DCE_TF

**Comment by Li-Chongyi** [comment]
Hi,

Thank you so much for the tensorflow version. The results look similar with ours. I will put the link to our project page.

发件人：Vo Van Tu <notifications@github.com>
发送日期：2020-08-07 15:58:40
收件人：Li-Chongyi/Zero-DCE <Zero-DCE@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[Li-Chongyi/Zero-DCE] Tensorflow Version (#8)

Hi,
Thank you for the good paper.
 I just re-produced your project here. Please kindly have a look and if there is any issue, please let me know.
https://github.com/tuvovan/Zero_DCE_TF
